### ISSUE TITLE
Specifying Category in List Views.

### ISSUE THREAD

**Issue by Bhupesh-V** [Bhupesh-V/tutorialdb#20]
Currently when we search without using filter, there is no indication whether it's a video, article etc.

**Comment by Bhupesh-V** [comment]
fixed in 9c388de

**Comment by Animesh-Ghosh** [comment]
Maybe we can also have the categories in `/tags/tag=<tagname>` and `/latest/` views?

**Comment by Animesh-Ghosh** [comment]
Closing this issue as it has been dealt with.
