### ISSUE TITLE
Search Results are getting rendererd when there is no search string

### ISSUE THREAD

**Issue by Bhupesh-V** [Bhupesh-V/tutorialdb#26]
**Describe the bug**

**To Reproduce**
1. Go to Home Page
2. Click on `Submit` button 
3. See error

**Expected behavior**
Search should not appear until unless there is a Search string

**Comment by Animesh-Ghosh** [comment]
I think a better way would be to handle searches similar to how search engines handle them.

If the input is empty, we don't submit the form to the back-end.

Something like:

__HTML:__
```html
<form onsubmit="return checkEmpty()" method="get">
.
.
.
</form>
```
__JS:__
```javascript
function checkEmpty() {
	var input = document.getElementById("search-bar");
	if (input.value == "" || input.value == null) {
		return false;
	}
	else {
		return true;
	}
}
```

Should I open a PR?

**Comment by Bhupesh-V** [comment]
I have done the same implementation
The submit buttons remains disabled until unless there is a string in input box

**Comment by Animesh-Ghosh** [comment]
So... [wontfix](https://github.com/Bhupesh-V/tutorialdb/labels/wontfix)?
