### ISSUE TITLE
setting up for deployment

### ISSUE THREAD

**Issue by Bhupesh-V** [Bhupesh-V/tutorialdb#33]
The SECRET_KEY which is commented by default may cause problems while deploying.
I propose we uncomment that and leave to user for generating a new key.
I found this [online service](https://www.miniwebtool.com/django-secret-key-generator/) and [one more](https://djecrety.ir/) for creating secret keys.

Other settings will remain same, user will create a `.env` file & add the key and LOCAL_IP in it

**Comment by Animesh-Ghosh** [comment]
OK, how about we uncomment the virtual environment variables, and direct the contributor to comment them and then generate their **`SECRET_KEY`**?

The main goal of commented virtual environment variables was to make setting-up easier, but I guess it's OK. Better to have deployment easier than to have setting-up easier.

**Comment by Bhupesh-V** [comment]
I will make the necessary changes in `settings.py` and `README`.

**Comment by Animesh-Ghosh** [comment]
Already created a PR.

**Comment by Bhupesh-V** [comment]
I am saying that we remove the method for creating a KEY, instead we provide a link to the online services discussed earlier.
User would then have to do 2 things.
1. Go to the online service for creating the SECRET_KEY
2. Add them in `.env` file
