### ISSUE TITLE
PWA fix

### ISSUE THREAD

**Issue by Bhupesh-V** [Bhupesh-V/tutorialdb#36]
**Describe the bug**
The PWA feature had been added previously but there seems to be some issue.

**Expected behavior**
An Add to Home Screen option should appear on android devices.

**Comment by viktorstrate** [comment]
@Bhupesh-V, I would like to work on this one 🚀

**Comment by Bhupesh-V** [comment]
@viktorstrate sure you can go ahead.
I am assigning this to you.
