### ISSUE TITLE
fix URL error when submitting long links

### ISSUE THREAD

**Issue by Bhupesh-V** [Bhupesh-V/tutorialdb#39]
**Describe the bug**
If we Contribute a link with more than 200 char length, its throwing up error.

**To Reproduce**
1. Go to [https://tutorialdb-app.herokuapp.com/contribute/](https://tutorialdb-app.herokuapp.com/contribute/)
2. Paste a legit link with more than 200 character length.
3. Press Submit.
4. See error.

**Additional context**
Fixing the model tag would fix the issue.

**Comment by gunjanraval** [comment]
Can you give an example link?

**Comment by iflare3g** [comment]
Hi, I'll fixi it.
URLField has max_length set to 200 by default.

**Comment by Animesh-Ghosh** [comment]
Wouldn't it be better to have the submitter shorten the link? Since URI lengths can be unlimited and certain browsers can only support URIs with length upto 2k characters?

**Comment by iflare3g** [comment]
At the moment , I've limited it to 300 chars.
