### ISSUE TITLE
Update CONTRIBUTING.md.

### ISSUE THREAD

**Issue by Animesh-Ghosh** [Bhupesh-V/tutorialdb#49]
PRs are being created without specifying what issue it is that they are solving.

Updating **CONTRIBUTING.md** to say that PRs may be created only if issues exist prior to it may be a possible solution.

For example, PRs #44, #45, #46 were created without any existing issue that they are supposed to solve. PRs  #41, #47 were created to solve issue #41.

**Comment by hstandeffer** [comment]
Hi @Animesh-Ghosh, I am trying to clone the repository but get this issue when running
`python manage.py test`:

\venv\lib\site-packages\django\contrib\staticfiles\storage.py", line 44, in path
    raise ImproperlyConfigured("You're using the staticfiles app "
django.core.exceptions.ImproperlyConfigured: You're using the staticfiles app without having set the STATIC_ROOT setting to a filesystem path.

Have you seen this issue before?

**Comment by Animesh-Ghosh** [comment]
I haven't run tests myself. I'll look into it.

**Comment by hstandeffer** [comment]
@Animesh-Ghosh Thank you, I've tried updating the static_dirs line, but am having no luck.

**Comment by Animesh-Ghosh** [comment]
@hstandeffer it would be better if you moved the conversation thread to its related Issue.

**Comment by hstandeffer** [comment]
Will do 👍

**Comment by liorbentov** [comment]
PR #43 solves this issue (not the contributing.md)

**Comment by Animesh-Ghosh** [comment]
Closing this issue for now, as #51 has been merged.
