### ISSUE TITLE
highlight current page no.

### ISSUE THREAD

**Issue by Bhupesh-V** [Bhupesh-V/tutorialdb#62]
**Describe the bug**
The current page is not highlighted when we search something.

**Expected behavior**
The current page should be highlighted/grayed out so that the user doesn't forget the current page number.

**Additional context**
Reading the documentation of [bulma.io](https://bulma.io/documentation/components/pagination/) may help.

**Comment by satya-vinay** [comment]
@Bhupesh-V I would like to work on it.

**Comment by Animesh-Ghosh** [comment]
You need to create a virtual environment using **`python3`** as:
```bash
$ python3 -m venv venv # create venv
$ source venv/bin/activate # activate venv
```
Then install requirements:
```bash
$ pip install -r requirements.txt # install dependecies
```

**Comment by perun-01** [comment]
thanks for helping Animesh-Ghosh

**Comment by perun-01** [comment]
results are not showing after search (locally)
so unable to see pagination

**Comment by Animesh-Ghosh** [comment]
You need to add a few tutorials first.

**Comment by chrisshyi** [comment]
I can take a shot at this as well

**Comment by perun-01** [comment]
how??

**Comment by Bhupesh-V** [comment]
The reason tutorials are not appearing in search results  is because they are not published.
You need to make a super user in django
login with your credentials by going to `/admin` and then change their status to publish.

**Comment by chrisshyi** [comment]
> The reason tutorials are not appearing in search results is because they are not published.
> You need to make a super user in django
> login with your credentials by going to `/admin` and then change their status to publish.

That solved it, thanks!

**Comment by perun-01** [comment]
> > The reason tutorials are not appearing in search results is because they are not published.
> > You need to make a super user in django
> > login with your credentials by going to `/admin` and then change their status to publish.
> 
> That solved it, thanks!

hey chrisshyi, could u pls share how u solve it.

**Comment by chrisshyi** [comment]
> > > The reason tutorials are not appearing in search results is because they are not published.
> > > You need to make a super user in django
> > > login with your credentials by going to `/admin` and then change their status to publish.
> > 
> > 
> > That solved it, thanks!
> 
> hey chrisshyi, could u pls share how u solve it.

Yeah sure. First, create a super user in Django by running  `python manage.py createsuperuser`, then log into the admin site at `127.0.0.1/admin`. From there, just click on the tutorials you've added and change their status to **published**
